name: Build OBS-FOV
description: OBS-FOV Build
on:
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation_linux:
    name: FOV - Build on Linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./.github/scripts/FOV/build_linux.sh

  check_program_compilation_windows:
    name: FOV - Build on Windows
    runs-on: [ self-hosted, windows, x64 ]

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./.github/scripts/FOV/build_windows.ps1
