name: FOV - Code analyzer

on:
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  code_analyzer:
    name: Code analyzer cppcheck
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate Build Files
        run: cmake --preset=ubuntu

      - name: Run cppcheck
        run: ./.github/scripts/FOV/run_cppcheck.sh

      - name: Publish cppcheck
        if: always()
        run: ./.github/scripts/FOV/cppcheck_publisher.sh