name: Commit Lint - OBS-FOV

on:
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  lint_commit:
    name: Check commit standard
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint
        run: |
          ./.github/scripts/FOV/commit_lint.sh
