name: Build OBS-FOV

on:
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation_linux:
    name: FOV - Build on Linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: ./.github/scripts/FOV/build_linux.sh

      - name: Upload Full Build Directory for Analyzer
        uses: actions/upload-artifact@v5
        with:
          name: linux-build-folder
          path: build/

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v5
        with:
          name: obs-fov-linux
          path: build/rundir/

  check_program_compilation_windows:
    name: FOV - Build on Windows
    runs-on: [ self-hosted, windows, x64 ]

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: ./.github/scripts/FOV/build_windows.ps1

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v5
        with:
          name: obs-fov-windows
          path: build_x64/rundir

  check_program_compilation_macos:
    name: FOV - Build on macOS
    runs-on: macos-latest

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: ./.github/scripts/FOV/build_macos.sh

  code_analyzer:
    name: Code analyzer cppcheck
    needs: check_program_compilation_linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Download Linux Build Folder
        uses: actions/download-artifact@v5
        with:
          name: linux-build-folder
          path: build/

      - name: Run cppcheck
        run: ./.github/scripts/FOV/run_cppcheck.sh

      - name: Publish cppcheck
        if: always()
        run: ./.github/scripts/FOV/cppcheck_publisher.sh