name: Build OBS-FOV

on:
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation_linux:
    name: FOV - Build on Linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build (Debug)
        run: ./.github/scripts/FOV/build_linux.sh

      - name: Upload Full Build Directory for Analyzer
        uses: actions/upload-artifact@v5
        with:
          name: linux-build-folder
          path: build/

      - name: Upload Linux Artifact (Debug)
        uses: actions/upload-artifact@v5
        with:
          name: FOV-linux-x64-debug
          path: build/rundir/

      - name: Build Release
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        run: ./.github/scripts/FOV/build_linux_release.sh

      - name: Upload Linux Release Artifact
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        uses: actions/upload-artifact@v5
        with:
          name: FOV-linux-x64-release
          path: build/rundir/

  check_program_compilation_windows:
    name: FOV - Build on Windows
    runs-on: [ self-hosted, windows, x64 ]

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build (Debug)
        run: ./.github/scripts/FOV/build_windows.ps1

      - name: Upload Windows Artifact (Debug)
        uses: actions/upload-artifact@v5
        with:
          name: FOV-windows-x64-debug
          path: build_x64/rundir

      - name: Build Release
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        run: ./.github/scripts/FOV/build_windows_release.ps1

      - name: Upload Windows Release Artifact
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        uses: actions/upload-artifact@v5
        with:
          name: FOV-windows-x64-release
          path: build_x64/rundir

  check_program_compilation_macos:
    name: FOV - Build on macOS
    runs-on: macos-15

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build (Debug)
        run: ./.github/scripts/FOV/build_macos.sh

      - name: Upload macOS Artifact (Debug)
        uses: actions/upload-artifact@v5
        with:
          name: FOV-macos-arm64-debug
          path: build/rundir/

      - name: Build Release
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        run: ./.github/scripts/FOV/build_macos_release.sh

      - name: Upload macOS Release Artifact
        if: github.ref_name == 'dev' || github.ref_name == 'master'
        uses: actions/upload-artifact@v5
        with:
          name: FOV-macos-arm64-release
          path: build/rundir/

  code_analyzer:
    name: Code analyzer cppcheck
    needs: check_program_compilation_linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Download Linux Build Folder
        uses: actions/download-artifact@v5
        with:
          name: linux-build-folder
          path: build/

      - name: Run cppcheck
        run: ./.github/scripts/FOV/run_cppcheck.sh

      - name: Publish cppcheck
        if: always()
        run: ./.github/scripts/FOV/cppcheck_publisher.sh

      - name: Upload cppcheck artifact
        uses: actions/upload-artifact@v5
        with:
          name: cppcheck
          path: check.txt